### ISSUE TITLE
Beta-test wallet android apk of build 1.0.8

### ISSUE THREAD

**Issue by Corresponsible** [velas/test-us#3]
### Scope

- Full Testing of all features available at [1.0.8 build of Velas Wallet (Android)](https://github.com/velas/test-us/blob/main/VellasWallet/Android/Velas%20Wallet%201.0.8.apk)
  - with a focus on main functionality that is relevant for a regular user in context of his daily activities

### Resources

[Official Docs](https://support.velas.com/hc/en-150/sections/360004308360-Questions-and-answers)

For Android Emulation:
Android Visual Studio: supports fingerprint ID, settings for apps
Nox Player: supports camera (for QR scanner)

### KNOWN BUGS

- Web version and android app minimum password length differ; android app not allowing cyrillic passwords (VLWA-136)
- Index account setting doesn't validate inputs, incorrect inputs freeze transactions history (VLWA-139)
- Translation mistake, in Spanish history tab has 'Enviar', should be 'Enviado' (VLWA-140)
- Translation mistake, in Ru\Ukr transaction details has 'Выполнено'\'Зроблено', should be 'Готово' (VLWA-141)
- Translation mistake, in Ukr wallets tab has 'Гаманьці', should be 'Гаманці' (VLWA-142)
- Not all buttons and alerts translated from En to other languages
- Language setting reset to English after app reload
- 'Setting up your wallet' overlaps 'Terms of Use' when creating new account when creating new account
- Need to reload app for fingerprint to start working
- Keyboard blocks 'next' button on smaller screens in 'restore account'
- If lock screen while setting fingerprint and go back to the app, applying fingerprint forces exit
- Applying incorrect fingerprint 5 times in a row forces 1 min cooldown but no alert
- Unlimited number length in 'send to'
- No 'split screen', 'floating window' support

### Rules

- you file new bugs in English as comments below according to the BUG TEMPLATE (see last section of this description)
- you do not file duplicates
- you do not edit your reports once they are reviewed (i.e. hidden), for any refinement\addition etc. you file a new bug starting with 'amends [old comment link]'
- you provide enough details to reproduce the bug
- you get a reward for valuable new bugs (we define the value of bugs, some guides we will share later on this topic)
- we reserve the right to modify the rules during the compaign
- once we review we will hide and mark comments as 'resolved', 'outdated', or 'duplicate' with the following meaning:
   - resolved - accepted as useful bug
   - outdated - the issue is already known or not a bug
   - duplicate - duplicate of 'known issues' or other comment

### BUG TEMPLATE

```markdown
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. Pay attention to '...' (if applicable)

**Expected result**
A clear and concise description of what you expected to happen.

**Actual result**
A clear and concise description of what happens.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10]
 - OS: [e.g. Android 10]
 - Browser [e.g. stock browser, chrome]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

```

### HIDDEN COMMENTS:

https://github.com/velas/test-us/issues/3#issuecomment-737544437 @Anthrax941 [resolved] +
https://github.com/velas/test-us/issues/3#issuecomment-738210638 @Anthrax941 [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-738321957 @Anthrax941 [resolved] -accuracy
https://github.com/velas/test-us/issues/3#issuecomment-738334374 @Anthrax941 [resolved]
https://github.com/velas/test-us/issues/3#issuecomment-738341751 @Andrii-Kalyniuk [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-738737196 @Anthrax941 [resolved]
https://github.com/velas/test-us/issues/3#issuecomment-738742704 @Anthrax941 [resolved]
https://github.com/velas/test-us/issues/3#issuecomment-739445114 @ohainet [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-739451020 @Andrii-Kalyniuk [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-739562846 @ohainet [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-740089895 @ohainet [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-739473661 @ohainet [outdated]
https://github.com/velas/test-us/issues/3#issuecomment-739254163 @Anthrax941 [resolved]
https://github.com/velas/test-us/issues/3#issuecomment-739502932 @ohainet [amends vlwa-139]

**Comment by Anthrax941** [comment]
**if the [fingerprint ID] menu is entered incorrect data 5 times (1) or the smartphone is locked and unlocked (2), then the cooldown is activated for 1 minute and there is no error message.**


**To Reproduce**
1. log in
2. Go to [Settings]
3. Go to [Fingerprint ID]
4. authenticate incorrect fingerprint 5 times(1) or block smartphone(2)
5.unlock smartphone(2)

**Actual result**
1)turns on cooldown for 1 minute, and no error massage
2)turns on cooldown for 1 minute

**Expected result**
1)Error massage "you entered incorrect data 5 times, please try again in 1 minute"
2)should not turn on cooldown

**Screenshots**
![S01202-222441](https://user-images.githubusercontent.com/73966415/100939395-e1d37000-34fe-11eb-8868-0b8d932b2b18.jpg)


**Smartphone**
 - Meizu M5c
 - OS: Android 7.0

**Comment by Anthrax941** [comment]
**confirmation dialog appears after transactions: 1. transfer amount is 0 
2.in the field to whom the current wallet is entered**

**Preconditions**

1, Log in
2.open any wallet

**To Reproduce**

1. Go to [Send]
    Enter data in the field [To]
    No enter data in the field [Amount]
    Click [Send]
2. Go to [Receive]
    Click [Copy]
    Go to [Send]
    Click entry field [To]
    Click [insert]
    Click [Send]

**Actual result**

Opened confirm dialog "Are you sure to send ....... "

**Expected result**
1)the button [Send] is not pressed, error massage "incorrect transfer amount"
2)the button [Send] is not pressed, error massage "invalid recipient"

**Screenshots**
![S01203-201544](https://user-images.githubusercontent.com/73966415/101072928-62e64200-35a7-11eb-974d-ce7326b97278.jpg)



Smartphone
Meizu M5c
OS: Android 7.0

**Comment by Anthrax941** [comment]
**uninformative message when: 1)incorrect characters in the [send] menu 2)entering the wrong recipient wallet**

**Preconditions**

1, Log in
2. open any wallet
3. Go to [Sand]
4.Click entry field [To]

**To Reproduce**

1.Enter characters( +, *, ...) in the field
2.Еnter incorrect data

**Actual result**

1.Еrror massege "Non-base58 character"
2.Еrror massege "Invalid checksum"

**Expected result**
1)Error massage "recipient's wallet cannot contain characters"
2)error massage "wallet not found"

**Screenshots**

![S01203-231237](https://user-images.githubusercontent.com/73966415/101089304-a64bab00-35bd-11eb-954f-974fe89a8cc7.jpg)
![S01203-201302](https://user-images.githubusercontent.com/73966415/101089306-a8156e80-35bd-11eb-8ae9-6551da5f5b5f.jpg)


**Smartphone**
Meizu M5c
OS: Android 7.0

**Comment by Anthrax941** [comment]
**The highlight field merges with a text**

**To Reproduce**

1.Find editable text
2.Highlight

**Actual result**

highlight field and text - white

**Expected result**

The highlight field no merges with a text

**Screenshots**
![S01203-232925](https://user-images.githubusercontent.com/73966415/101091100-5de1bc80-35c0-11eb-9996-4fbadd15cccc.jpg)
![S01203-233141](https://user-images.githubusercontent.com/73966415/101091108-60441680-35c0-11eb-82a4-8578f94a3c73.jpg)
![S01203-225249](https://user-images.githubusercontent.com/73966415/101091115-61754380-35c0-11eb-9fb5-0853fba8fa74.jpg)


**Smartphone**
Meizu M5c
OS: Android 7.0

**Comment by Andrii-Kalyniuk** [comment]
**Too simple passwords (like '123456') are allowed for setup**

**To Reproduce**
1. Run app after installation
2. Fill in the 'Password' field in the 'Setup Password' form with value '123456'
3. Tap 'Next'

**Expected result**
Message: 'Your password is too weak'

**Actual result**
Registration procedure continues


**Smartphone:**
 - Xiaomi Mi9T
 - Android 10
 - Mobile Wallet 1.0.8

**Comment by Anthrax941** [comment]
**fingerprint login disappears from login screen if you enter wrong fingerprint 5 times  and close the app within 1 minute**

**To Reproduce**

1.Log in
2.Go to [Settings]
3.Go to [fingerprint ID]
4.Set fingerprint
5.Restart app
6.Login by fingerprint
7.Go to [Settings]
8.Go to [fingerprint ID]
9.Applying incorrect fingerprint 5 times
10.Restart app within a 1 minute

**Actual result**

no fingerprint login on the login screen

**Expected result**

fingerprint login is saved on the login screen

**Smartphone**
Meizu M5c
OS: Android 7.0

**Comment by Anthrax941** [comment]
**every second click on the menu [fingerprint ID] does not open it**

**To Reproduce**

1.Log in
2.Go to [Settings]
3.Go to [fingerprint ID]
4.Set fingerprint
5.Go to [fingerprint ID]

**Actual result**

the menu opens for a split second and closes, if you restart the application after incorrectly opening the menu, the fingerprint login disappears

**Expected result**

the menu opens

**Smartphone**
Meizu M5c
OS: Android 7.0

**Comment by Anthrax941** [comment]
**Wallet(account) number saved after [Log out] -> [Log in], but after reload app is reset from [Account # 1]**

**To Reproduce**

1.Log in
2.Go to [Settings]
3.Сhange [Account # 1] on [Account # ...]
4.Close app
5.Open app
6.Log in
7.Go to [Settings]

**Actual result**

[Account # 1]

**Expected result**

Wallet number is saved

**Screenshots:**
![S01205-155248](https://user-images.githubusercontent.com/73966415/101244945-297e1580-3712-11eb-8b4d-d25c58770402.jpg)


**Smartphone**
Meizu M5c
OS: Android 7.0

**Comment by ohainet** [comment]
**Describe the bug**

Application crashes with an error message when turn off a split screen mode.

**To Reproduce**

1. Launch application in split screen mode.
2. Exit split screen mode.

**Expected result**

Application should go into operational full screen mode.

**Actual result**

Application crashes with an error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/73889525/101269764-d2605b00-377a-11eb-98fc-3bcc87418485.png)
![image](https://user-images.githubusercontent.com/73889525/101269724-7b5a8600-377a-11eb-8ef5-804aeb23f0cd.png)
![image](https://user-images.githubusercontent.com/73889525/101269788-12bfd900-377b-11eb-821c-86e55fcbb901.png)

**Smartphone:**

- Device: Xiaomi Redmi Note 4X
- OS: Android 7.0 (MI 11.0.2 global) 

**Additional context**

Application window location (top or bottom) and method of split-screen mode exit (button or swipe) does not alter the application behavior (crash).

**Comment by Andrii-Kalyniuk** [comment]
**Incorrect display of UI elements in floating window mode**

**To Reproduce**
1. Launch the app
2. Switch the app to floating window mode

**Expected result**
When the size of the app window decreases, the interface elements proportionally decrease their size and retain their relative position.

**Actual result**
The wallets icons are overlapped by the 'Balance $'.
'Send', 'Scan', 'Receive' buttons are not displayed in wallets. 

**Screenshots**
![Balance_overlapped](https://user-images.githubusercontent.com/39514114/101270885-40f6e600-3786-11eb-99fe-2b6f88b32da7.jpg)
![Send_Scan_Recieve_notDisplayed](https://user-images.githubusercontent.com/39514114/101271283-258dda00-378a-11eb-8277-61ed7e15dac2.png)

**Smartphone:**
 - Device: Xiaomi Mi9T
 - OS: Android 10(MIUI Global 12.0.5 Stable)
 - Mobile Wallet 1.0.8

**Comment by ohainet** [comment]
**Bug description**

Application's on-screen navigation buttons moves up and overlaps top of the on-screen keyboard.

**To Reproduce**

1. Go to 'Settings'
2. Invoke on-screen keyboard
3. Pay attention to application on-screen navigation buttons element

**Expected result**

Get on-screen keyboard with full usability.

**Actual result**

On-screen keyboard with inaccessible top row.

**Screenshots**

![image](https://user-images.githubusercontent.com/73889525/101275657-e5d9e900-37af-11eb-94be-7f8aef853c80.png)
![image](https://user-images.githubusercontent.com/73889525/101275697-5a148c80-37b0-11eb-9d3c-e943f0a5a714.png)
![image](https://user-images.githubusercontent.com/73889525/101275675-13269700-37b0-11eb-8d53-e94fa7b86a0f.png)


**Smartphone:**

- Device: Xiaomi Redmi Note 4X
- OS: Android 7.0 (MI 11.0.2 global)

**Additional context**

Accidental navigation buttons clicks occur while using on-screen keyboard so 'Settings' window crash.

**Comment by ohainet** [comment]
**Bug description**

Application changes some end part of input field value into ‘0’ and uses E notation way to express too large numbers. 

**To Reproduce**

1. Go to ‘Settings’
2. Go to ‘Account # input field’
3. Input at least 18 any numeric 
4. Press ‘Enter’
5. Pay attention to the result in the input field
6. Then input 22 or more any numeric 
7. Press ‘Enter’
8. Pay attention to the result in the input field

**Expected result**

The application enters the value of every 18 and subsequent characters without changing or enters the value of too large number equal to the inputted one, otherwise a message about exceeding allowed limit of characters.

**Actual result**

The application changes the value of each 18 and subsequent characters to "0" and converts too large numbers into scientific notation using "e" letter in the input field.

**Screenshots**

![image](https://user-images.githubusercontent.com/73889525/101281414-62cc8900-37d7-11eb-9489-e9cc235d5ddf.png)
![image](https://user-images.githubusercontent.com/73889525/101281447-90193700-37d7-11eb-8340-ae68e90042d6.png)

**Smartphone:**

- Device: Xiaomi Redmi Note 4X
- OS: Android 7.0 (MI 11.0.2 global)

**Comment by ohainet** [comment]
**Bug description**

Application does not allow a correct split screen mode, which provides smartphone functionality.

**To Reproduce**

1. Launch application in split screen mode.
2. Pay attention to the login screen view.

**Expected result**

Get login screen completely ready to perform its functionality.

**Actual result**

Application does not fully display login screen in split screen mode. 
The "Next" and "New Account" buttons are not visible. 
User needs to enlarge login window to access these buttons, practically turn off split screen mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/73889525/101292094-0dfc3300-3816-11eb-9470-85b8a8083270.png)
![image](https://user-images.githubusercontent.com/73889525/101292132-4bf95700-3816-11eb-8ff9-aad68220ce3c.png)

**Smartphone:**

- Device: Xiaomi Redmi Note 4X
- OS: Android 7.0 (MI 11.0.2 global)

**Comment by ohainet** [comment]
**Bug description**

Application does not correctly position screen elements in split screen mode.

**To Reproduce**

1. Launch application.
2. Login.
3. Go to split screen mode.
4. Pay attention to the screen view.

**Expected result**

Get application screen have elements correctly positioned.

**Actual result**

Application overlays its elements displayed on the screen on top of each other.

**Screenshots**

![image](https://user-images.githubusercontent.com/73889525/101388236-57a55600-38c8-11eb-9c99-61afff298708.png)

**Smartphone:**

- Device: Xiaomi Redmi Note 4X
- OS: Android 7.0 (MI 11.0.2 global)
